onlyBuiltDependencies:
  - '@serialport/bindings-cpp'
  - cpu-features
  - electron
  - esbuild
  - ffmpeg-static
  - node-pty
  - ssh2
  - vue-demi
ignoredBuiltDependencies:
  - onnxruntime-node
overrides:
  node-abi: ^3.94.0
