import type { Component } from 'vue'
import {
  Aim,
  Compass,
  Connection,
  Cpu,
  DataAnalysis,
  Grid,
  Lightning,
  Location,
  MapLocation,
  Monitor,
  Odometer,
  PieChart,
  Platform,
  Promotion,
  SetUp,
  Setting,
  Tools,
  TrendCharts,
  Van,
  VideoCamera,
} from '@element-plus/icons-vue'
import type { ApplicationIcon } from '@/core/panels/registry'

export const applicationIconComponents: Record<ApplicationIcon, Component> = {
  grid: Grid,
  trend: TrendCharts,
  position: Location,
  motor: SetUp,
  camera: VideoCamera,
  robot: Platform,
  satellite: Promotion,
  compass: Compass,
  data: DataAnalysis,
  monitor: Monitor,
  settings: Setting,
  connection: Connection,
  power: Lightning,
  vehicle: Van,
  tools: Tools,
  cpu: Cpu,
  map: MapLocation,
  target: Aim,
  gauge: Odometer,
  chart: PieChart,
}

export const applicationIconOptions: readonly { value: ApplicationIcon; label: string }[] = [
  { value: 'grid', label: 'app.icon.grid' },
  { value: 'trend', label: 'app.icon.trend' },
  { value: 'chart', label: 'app.icon.chart' },
  { value: 'data', label: 'app.icon.data' },
  { value: 'monitor', label: 'app.icon.monitor' },
  { value: 'position', label: 'app.icon.position' },
  { value: 'map', label: 'app.icon.map' },
  { value: 'compass', label: 'app.icon.compass' },
  { value: 'satellite', label: 'app.icon.satellite' },
  { value: 'target', label: 'app.icon.target' },
  { value: 'motor', label: 'app.icon.motor' },
  { value: 'robot', label: 'app.icon.robot' },
  { value: 'vehicle', label: 'app.icon.vehicle' },
  { value: 'camera', label: 'app.icon.camera' },
  { value: 'connection', label: 'app.icon.connection' },
  { value: 'power', label: 'app.icon.power' },
  { value: 'cpu', label: 'app.icon.cpu' },
  { value: 'gauge', label: 'app.icon.gauge' },
  { value: 'tools', label: 'app.icon.tools' },
  { value: 'settings', label: 'app.icon.settings' },
]
