import type { Component } from 'vue'
import {
  Aim,
  Compass,
  Connection,
  Cpu,
  DataAnalysis,
  Grid,
  Lightning,
  Location,
  MapLocation,
  Monitor,
  Odometer,
  PieChart,
  Platform,
  Promotion,
  SetUp,
  Setting,
  Tools,
  TrendCharts,
  Van,
  VideoCamera,
} from '@element-plus/icons-vue'
import type { ApplicationIcon } from '@/core/panels/registry'

export const applicationIconComponents: Record<ApplicationIcon, Component> = {
  grid: Grid,
  trend: TrendCharts,
  position: Location,
  motor: SetUp,
  camera: VideoCamera,
  robot: Platform,
  satellite: Promotion,
  compass: Compass,
  data: DataAnalysis,
  monitor: Monitor,
  settings: Setting,
  connection: Connection,
  power: Lightning,
  vehicle: Van,
  tools: Tools,
  cpu: Cpu,
  map: MapLocation,
  target: Aim,
  gauge: Odometer,
  chart: PieChart,
}

export const applicationIconOptions: readonly { value: ApplicationIcon; label: string }[] = [
  { value: 'grid', label: '工作台' },
  { value: 'trend', label: '趋势' },
  { value: 'chart', label: '图表' },
  { value: 'data', label: '数据' },
  { value: 'monitor', label: '监控' },
  { value: 'position', label: '定位' },
  { value: 'map', label: '地图' },
  { value: 'compass', label: '导航' },
  { value: 'satellite', label: '卫星' },
  { value: 'target', label: '目标' },
  { value: 'motor', label: '电机' },
  { value: 'robot', label: '机器人' },
  { value: 'vehicle', label: '车辆' },
  { value: 'camera', label: '相机' },
  { value: 'connection', label: '连接' },
  { value: 'power', label: '电源' },
  { value: 'cpu', label: '计算' },
  { value: 'gauge', label: '仪表' },
  { value: 'tools', label: '工具' },
  { value: 'settings', label: '设置' },
]
